//! PHP configuration generation (php.ini, php-fpm.conf, env, extensions).
//!
//! Moved verbatim from the former monolithic `manager.rs` (code-health M-01).

use super::*;

/// Generate a basic php.ini
pub(super) fn generate_php_ini(
    path: &PathBuf,
    paths: &RuntimePaths,
    web_port: u16,
    mysql_port: u16,
    postgresql_port: u16,
) -> Result<(), String> {
    // Get the PHP directory (parent of php_cgi binary) to find the ext folder
    let php_dir = paths
        .php_cgi
        .parent()
        .ok_or("Cannot determine PHP directory")?;

    // On Windows, extensions are in the ext/ subdirectory relative to PHP binary
    // Use absolute path with forward slashes (PHP accepts forward slashes on Windows)
    let ext_dir = php_dir.join("ext");
    let ext_dir_str = ext_dir.to_string_lossy().replace('\\', "/");

    // Get error log and session paths
    let error_log = paths
        .logs_dir
        .join("php-errors.log")
        .to_string_lossy()
        .replace('\\', "/");
    let session_dir = paths.logs_dir.join("php-sessions");
    fs::create_dir_all(&session_dir).map_err(|e| {
        format!(
            "Failed to create PHP session directory {}: {}",
            session_dir.display(),
            e
        )
    })?;
    let session_path = session_dir.to_string_lossy().replace('\\', "/");

    let extension_lines = php_ini_extension_lines(&ext_dir);
    let env_file = generate_php_env_file(paths, web_port, mysql_port, postgresql_port)?;
    let env_file_path = env_file.to_string_lossy().replace('\\', "/");

    let php_ini_content = format!(
        r#"; CHAMP PHP Configuration
; Basic PHP settings for development

[PHP]
; Error reporting - tuned for local development
error_reporting = E_ALL & ~E_DEPRECATED & ~E_WARNING
display_errors = On
display_startup_errors = Off
log_errors = On
error_log = "{}"

; Maximum execution time
max_execution_time = 300
max_input_time = 300

; Memory limit
memory_limit = 256M

; POST data limit
post_max_size = 100M
upload_max_filesize = 100M
max_input_vars = 5000

; Date timezone
date.timezone = UTC

; Extensions - use absolute path for reliability
; Note: PDO, zlib, and session are built-in to bundled PHP builds.
extension_dir = "{}"
{}

; CHAMP database defaults for projects that do not specify a MySQL port.
auto_prepend_file = "{}"
mysqli.default_host = 127.0.0.1
mysqli.default_port = {}
pgsql.default_host = 127.0.0.1
pgsql.default_port = {}

; Session settings - use absolute path for Windows compatibility
session.save_path = "{}"
session.cookie_httponly = 1
session.use_strict_mode = 1
session.use_cookies = 1
session.use_trans_sid = 0

; File uploads
upload_tmp_dir = "{}"

; CGI settings
cgi.force_redirect = 0
cgi.fix_pathinfo = 1

; Security settings
expose_php = Off

; OPcache/JIT is disabled for FastCGI runtime stability.
opcache.enable=0
opcache.enable_cli=0
opcache.jit=off
opcache.jit_buffer_size=0

; Realpath cache for better file path resolution (doubled)
realpath_cache_size=8192K
realpath_cache_ttl=300
"#,
        error_log,
        ext_dir_str,
        extension_lines,
        env_file_path,
        mysql_port,
        postgresql_port,
        session_path,
        session_path
    );

    let mut file = File::create(path).map_err(|e| format!("Failed to create php.ini: {}", e))?;
    file.write_all(php_ini_content.as_bytes())
        .map_err(|e| format!("Failed to write php.ini: {}", e))?;

    Ok(())
}

pub(super) fn generate_php_env_file(
    paths: &RuntimePaths,
    web_port: u16,
    mysql_port: u16,
    postgresql_port: u16,
) -> Result<PathBuf, String> {
    let env_file = paths.config_dir.join("champ-env.php");
    let content = format!(
        r#"<?php
// Generated by CHAMP. This file is loaded before project PHP scripts.
$champMysqlHost = '127.0.0.1';
$champMysqlPort = '{}';
$champPostgresHost = '127.0.0.1';
$champPostgresPort = '{}';
$champWebPort = '{}';

putenv('CHAMP_MYSQL_HOST=' . $champMysqlHost);
putenv('CHAMP_MYSQL_PORT=' . $champMysqlPort);
putenv('CHAMP_MYSQL_USER=root');
putenv('CHAMP_MYSQL_PASSWORD=');
putenv('CHAMP_POSTGRES_HOST=' . $champPostgresHost);
putenv('CHAMP_POSTGRES_PORT=' . $champPostgresPort);
putenv('CHAMP_POSTGRES_USER=postgres');
putenv('CHAMP_POSTGRES_PASSWORD=');
putenv('CHAMP_WEB_PORT=' . $champWebPort);
putenv('MYSQL_TCP_PORT=' . $champMysqlPort);
putenv('PGHOST=' . $champPostgresHost);
putenv('PGPORT=' . $champPostgresPort);
putenv('PGUSER=postgres');
putenv('PGPASSWORD=');

$_SERVER['CHAMP_MYSQL_HOST'] = $champMysqlHost;
$_SERVER['CHAMP_MYSQL_PORT'] = $champMysqlPort;
$_SERVER['CHAMP_MYSQL_USER'] = 'root';
$_SERVER['CHAMP_MYSQL_PASSWORD'] = '';
$_SERVER['CHAMP_POSTGRES_HOST'] = $champPostgresHost;
$_SERVER['CHAMP_POSTGRES_PORT'] = $champPostgresPort;
$_SERVER['CHAMP_POSTGRES_USER'] = 'postgres';
$_SERVER['CHAMP_POSTGRES_PASSWORD'] = '';
$_SERVER['CHAMP_WEB_PORT'] = $champWebPort;

defined('CHAMP_MYSQL_HOST') || define('CHAMP_MYSQL_HOST', $champMysqlHost);
defined('CHAMP_MYSQL_PORT') || define('CHAMP_MYSQL_PORT', (int) $champMysqlPort);
defined('CHAMP_MYSQL_USER') || define('CHAMP_MYSQL_USER', 'root');
defined('CHAMP_MYSQL_PASSWORD') || define('CHAMP_MYSQL_PASSWORD', '');
defined('CHAMP_POSTGRES_HOST') || define('CHAMP_POSTGRES_HOST', $champPostgresHost);
defined('CHAMP_POSTGRES_PORT') || define('CHAMP_POSTGRES_PORT', (int) $champPostgresPort);
defined('CHAMP_POSTGRES_USER') || define('CHAMP_POSTGRES_USER', 'postgres');
defined('CHAMP_POSTGRES_PASSWORD') || define('CHAMP_POSTGRES_PASSWORD', '');
defined('CHAMP_WEB_PORT') || define('CHAMP_WEB_PORT', (int) $champWebPort);
"#,
        mysql_port, postgresql_port, web_port
    );

    fs::write(&env_file, content).map_err(|e| {
        format!(
            "Failed to write CHAMP PHP environment file {}: {}",
            env_file.display(),
            e
        )
    })?;

    Ok(env_file)
}

pub(super) fn apply_php_database_env(
    command: &mut Command,
    web_port: u16,
    mysql_port: u16,
    postgresql_port: u16,
) {
    let mysql_port = mysql_port.to_string();
    let postgresql_port = postgresql_port.to_string();
    command
        .env("CHAMP_MYSQL_HOST", "127.0.0.1")
        .env("CHAMP_MYSQL_PORT", &mysql_port)
        .env("CHAMP_MYSQL_USER", "root")
        .env("CHAMP_MYSQL_PASSWORD", "")
        .env("CHAMP_POSTGRES_HOST", "127.0.0.1")
        .env("CHAMP_POSTGRES_PORT", &postgresql_port)
        .env("CHAMP_POSTGRES_USER", "postgres")
        .env("CHAMP_POSTGRES_PASSWORD", "")
        .env("CHAMP_WEB_PORT", web_port.to_string())
        .env("MYSQL_TCP_PORT", mysql_port)
        .env("PGHOST", "127.0.0.1")
        .env("PGPORT", postgresql_port)
        .env("PGUSER", "postgres")
        .env("PGPASSWORD", "");
}

pub(super) fn php_ini_extension_lines(ext_dir: &Path) -> String {
    [
        "curl",
        "mbstring",
        "mysqli",
        "openssl",
        "pdo_mysql",
        "pgsql",
        "pdo_pgsql",
    ]
    .iter()
    .filter(|extension| php_extension_available(ext_dir, extension))
    .map(|extension| format!("extension={}", extension))
    .collect::<Vec<_>>()
    .join("\n")
}

#[cfg(target_os = "windows")]
pub(super) fn php_extension_available(ext_dir: &Path, extension: &str) -> bool {
    ext_dir.join(format!("php_{}.dll", extension)).exists()
}

#[cfg(not(target_os = "windows"))]
pub(super) fn php_extension_available(_ext_dir: &Path, _extension: &str) -> bool {
    true
}

/// Generate php-fpm.conf for static-php builds
pub(super) fn generate_php_fpm_conf(
    path: &PathBuf,
    paths: &RuntimePaths,
    php_port: u16,
) -> Result<(), String> {
    // Get current username from environment
    let user = std::env::var("USER")
        .or_else(|_| std::env::var("USERNAME"))
        .unwrap_or_else(|_| "nobody".to_string());

    let fpm_conf_content = format!(
        r#"; CHAMP PHP-FPM Configuration
; Optimized for local PHP development

[global]
error_log = {logs_dir}/php-fpm.log
log_level = warning

[www]
user = {user}
group = {user}
listen = 127.0.0.1:{php_port}
listen.owner = {user}
listen.group = {user}
listen.mode = 0660

; Process manager - static for better performance (no spawning delays)
pm = static
pm.max_children = 10

; Worker recycling to prevent memory leaks
pm.max_requests = 1000

; Request settings for local tools and projects
request_terminate_timeout = 300
php_admin_value[error_log] = {logs_dir}/php-fpm.log
php_admin_flag[log_errors] = on
php_value[session.save_path] = {logs_dir}/php-sessions

; Performance tuning
php_value[memory_limit] = 256M
"#,
        logs_dir = paths.logs_dir.display().to_string().replace('\\', "/"),
        user = user,
        php_port = php_port,
    );

    let mut file =
        File::create(path).map_err(|e| format!("Failed to create php-fpm.conf: {}", e))?;
    file.write_all(fpm_conf_content.as_bytes())
        .map_err(|e| format!("Failed to write php-fpm.conf: {}", e))?;

    Ok(())
}
